spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.170:1521:xe
    username: RUANJIAYU
    password: 123456
    dbcp2:
      validation-query: select 1 from dual
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    database: oracle
